server:
  port: 8080

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

#freemarker

  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    template-loader-path: classpath:/views/
    settings:
      classic_compatible: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  #mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.qiu.pojo
  configuration:
    map-underscore-to-camel-case: true

#pageHelper


